<?php
/**
 * @category    Inchoo
 * @package     Inchoo_Reinvigorate
 * @author      Branko Ajzele <ajzele@gmail.com>
 * @copyright   Copyright (c) Inchoo
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script type="text/javascript">
    var re_name_tag = "<?php echo sprintf('#%s - %s', $this->getCustomer()->getId(), $this->getCustomer()->getName()) ?>";
</script>