<?php
/**
 * @category    Inchoo
 * @package     Inchoo_Reinvigorate
 * @author      Branko Ajzele <ajzele@gmail.com>
 * @copyright   Copyright (c) Inchoo
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script type="text/javascript" src="http://include.reinvigorate.net/re_.js"></script>
<script type="text/javascript">
    try {
        reinvigorate.track("<?php echo $this->helper('inchoo_reinvigorate')->getApiKey() ?>");
    } catch (err) {
    }
</script>